=== bertyhell/kohtopa/trunk/KohtopaDesktop/language.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="competitie">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="entry" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="entry">
        <xs:complexType mixed="true">
            <xs:attribute name="name" type="xs:NMTOKEN" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== bertyhell/kohtopa/KohtopaWeb/testlanguage_EN.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<competitie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="language.xsd">
    <entry name="titleJFrameDesktopMain">Kohtopa Desktop Application</entry>
    <entry name="errWriteLangFile">failed to write language file</entry>
    <entry name="errLookAndFeelNotFound">Failed to locate look and feel nimbus\\nYou need version 1.6_18 of jre for smooth look and feel</entry>
    <entry name="errWriteLangFileTitle">language fail</entry>
    <entry name="titleCalendar">Calendar</entry>
    <entry name="errLookAndFeelNotFoundTitle">Look and Feel not found</entry>
    <entry name="titleAddRemove">Add / Remove</entry>
</competitie>
